name: actions-demo
on: [push]
jobs:
  Ubuntu-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered first job - $GITHUB_JOB"
      - name: Checkout repo code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repo has been cloned to the runner."
      - run: echo "Current branch is $GITHUB_REF."
      - run: sh ${{ github.workspace }}/bin/hello_world.sh
  Windows-GitHub-Action:
    runs-on: windows-latest
    steps:
      - run: Write-Host "$Env:GITHUB_JOB"
      - run: pwsh -Command 1..10
  Ubuntu-GitHub-Action-2:
    needs: Ubuntu-GitHub-Action
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered first dependent job - $GITHUB_JOB"
      - name: Checkout repo code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repo has been cloned to the runner."
      - run: echo "Current branch is $GITHUB_REF."
      - run: sh ${{ github.workspace }}/bin/hello_world.sh
  Ubuntu-GitHub-Action-3:
    needs: Ubuntu-GitHub-Action-2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered second dependent job - $GITHUB_JOB"
      - name: Checkout repo code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repo has been cloned to the runner."
      - run: echo "Current branch is $GITHUB_REF."
      - run: sh ${{ github.workspace }}/bin/hello_world.sh
  